### ISSUE TITLE
TODO for 0.05

### ISSUE THREAD

**Issue by alejzeis** [BlockServerProject/BlockServer#11]
TODO:
- \- [x] Write skeleton server
- \- [x] Organize Project

Login Packets to be implemented:
- [x] ID_CONNECTED_PING_OPEN_CONNECTIONS (0x01)
- [x] ID_UNCONNECTED_PING_OPEN_CONNECTIONS (0x01c)
- [x] ID_OPEN_CONNECTION_REQUEST_1 (0x05)
- [x] ID_OPEN_CONNECTION_REPLY_1 (0x06)
- [x] ID_OPEN_CONNECTION_REQUEST_2 (0x07)
- [x] ID_OPEN_CONNECTION_REPLY_2 (0x08)
- [ x ] ID_INCOMPATIBLE_PROTOCOL_VERSION (0x1a)
- [x] ID_UNCONNECTED_PING_OPEN_CONNECTIONS (0x1c)
