### ISSUE TITLE
TODO list for current version

### ISSUE THREAD

**Issue by PEMapModder** [BlockServerProject/BlockServer#112]
Curent version: beta 1.0.0

Code level:
- [x] Basic structure of starting a new `Server` instance
- [x] Scheduling (ServerTicker) system
- [ ] Dynamic protocol registration
  - [ ] MCPE protocol
    - [x] RakNet packets
      - [x] Unconnected and advertizement packets (0x01, 0x02, 0x1C, 0x1D)
      - [x] Open connection conversation (0x05, 0x06, 0x07, 0x08)
      - [x] Packet encapsulation format (inside the protocol, not at the `Client` class)
      - [x] ACK and NACK
    - [ ] MCPE packets
      - [ ] Login and spawn packets
      - [ ] If possible, support multiple protocol versions
      - [ ] `L.P.` Chat support
- [ ] Console reading
- [x] Console logging

Debug/Setup level:
- [x] Server can start and stop gracefully
- [ ] The things in code level are working (when debugging starts, copy above to here)
- [x] Maven setup

Effect level:
- [x] Advertize to clients of the same network if on port 19132
- [ ] Can spawn to a world, whether that is a actual world or not
- [ ] Console commands

Keys:
`L.P.`: Low Priority
`R.F.C.`: Request For Comments (comment below)

**Comment by jython234** [comment]
@PEMapModder I just realized that my encapsulation code is not correct. I still have much to learn...

**Comment by jython234** [comment]
Hey everyone,

I have a goal for all of us to work on. Since we are pretty close to finishing our TODO for beta 1.0, I would like us to at least release this version before December this year. Yes, you may say "what type of goal is this?", but we still have some hard things to finish (chunk sending).

We can also raise or lower the goal too.

Thank you,
- jython234

**Comment by jython234** [comment]
Also, In order to complete some other things (chat support), we could use my own MCPE client here: https://github.com/jython234/MagicClient. This is primarily because we can't get the vanilla client to work with our chunk packets. So we can use this client to test chat and other things.

**Comment by jython234** [comment]
@PEMapModder What happened to console reading?

**Comment by PEMapModder** [comment]
@jython234 what's wrong?

**Comment by optrusty** [comment]
Hey anyone notice the domain is not resolving

**Comment by jython234** [comment]
Irc

**Comment by optrusty** [comment]
k
