### ISSUE TITLE
TODO: Priorities

### ISSUE THREAD

**Issue by jython234** [BlockServerProject/BlockServer#133]
## Priorities List

**Note:** If you want to modify this list, please edit my comment here, and **comment below with your revisions**. Thank you.

- [ ] Chunk Sending (**HIGH PRIORITY**, #131 )
- [ ] Internal API -> Connection with PB (**NORMAL PRIORITY**, #129 )
- [ ]  Chat Support (**NORMAL PRIORITY**)

**Comment by Falkirks** [comment]
This looks good. I modified your post to make it more readable.

**Comment by jython234** [comment]
@Falkirks thank you. I was in a hurry, and I'm not the best with markdown :).

**Comment by PEMapModder** [comment]
Chat support revision: low :arrow_right: normal priority
Also, I self-assign chat, after chat data packets can be received.

**Comment by jython234** [comment]
@PEMapModder, meh not happening xD. (Chat packets)

On Tuesday, February 24, 2015, PEMapModder <notifications@github.com> wrote:

> Chat support revision: low [image: :arrow_right:] normal priority
> Also, I self-assign chat, after chat data packets can be received.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BlockServerProject/BlockServer/issues/133#issuecomment-75788527>
> .
>


--
