### ISSUE TITLE
[TODO]: Version 0.1

### ISSUE THREAD

**Issue by alejzeis** [BlockServerProject/BlockServer#14]
Master: [![Build Status](https://travis-ci.org/BlockServerProject/BlockServer.svg?branch=master)](https://travis-ci.org/BlockServerProject/BlockServer)

Level Rewrite: [![Build Status](https://travis-ci.org/BlockServerProject/BlockServer.svg?branch=level-rewrite)](https://travis-ci.org/BlockServerProject/BlockServer)
## Things to be implemented before v0.1.0
- [x] Implement encoding, decoding data packets.
- [x] Implement Ping-Pong System
  - [x] Implement Ping Class
  - [x] Implement Pong Class
- [x] Implement handshake.
  - [x] Complete ClientConnect
  - [x] Complete ServerHandshake
  - [x] Complete ClientHandshake
  - [ ] Complete Chunk Sending \*  Completed on LevelRewrite.
  - [x] Complete StartGame
- [ ] Implement Level, Chunk, LevelDB
- [x] Implement NBT
- [x] Get the player to spawn.
- [x] Players see each other (Planning for Saturday)
## PLEASE DO NOT USE THIS AS A FORUM

Go to the [BeaconMine forums](http://beaconpe.net/forums) :).
