### ISSUE TITLE
[TODO]:  World Gen.

### ISSUE THREAD

**Issue by MalekAlrwily** [BlockServerProject/BlockServer#36]
[![Build Status](https://travis-ci.org/BlockServerProject/BlockServer.svg?branch=master)](https://travis-ci.org/BlockServerProject/BlockServer)
Here is To-do tasks for World Generation:
- [ ] Create World class
- [ ] Create world related files
- [ ] Add all world generation methods to Generator class
- [ ] Create FlatGenerator class
- [ ] Load LevelDB.
