### ISSUE TITLE
Level Rewrite TODO

### ISSUE THREAD

**Issue by alejzeis** [BlockServerProject/BlockServer#96]
Level Rewrite: [![Build Status](https://travis-ci.org/BlockServerProject/BlockServer.svg?branch=level-rewrite)](https://travis-ci.org/BlockServerProject/BlockServer)
# TODO:
- [ ] Implement level saving
  - [ ] Anvil format
  - [x] BlockServer level format
- [x] Implement FullChunkData Packet
- [ ] Implement Flat World Generator.
